[package]
edition = "2021"
name = "rbtc"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.11.0"
futures = "0.3.21"
socket2 = "0.4.4"
